openapi: 3.0.0
info:
  title: api
  version: 0.1.0
paths:
  /get/charts:
    get:
      tags:
      - Data
      description: Get prices
      operationId: get_charts
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                  format: uint32
                  minimum: 0.0
  /get/news:
    get:
      tags:
      - Data
      operationId: get_news
      responses:
        '200':
          description: ''
          content:
            text/plain:
              schema:
                type: string
  /user/delete:
    post:
      tags:
      - User
      operationId: delete
      responses:
        '200':
          description: ''
          content:
            text/plain:
              schema:
                type: string
  /signup:
    post:
      tags:
      - User
      operationId: signup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
        required: true
      responses:
        '200':
          description: ''
        '404':
          description: Unauthorized access
        '500':
          description: Internal server error
        '409':
          description: Email already registered
  /login:
    post:
      tags:
      - User
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
        required: true
      responses:
        '200':
          description: ''
        '404':
          description: Unauthorized access
        '500':
          description: Internal server error
        '409':
          description: Email already registered
components:
  schemas:
    UserCredentials:
      type: object
      required:
      - email
      - password_hash
      properties:
        email:
          type: string
        password_hash:
          type: string
