# .github/workflows/release_master.yml
name: Release Master

on:
  push:
    branches: [master]
    paths:
      - /openapi.yaml
      - /mobile/**

  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    # TODO: Use if we get nixos workers
    # runs-on: nixos-23.11  # Official NixOS runner
    steps:
      - uses: actions/checkout@v4
      # Nix setup
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      # No need for Nix installation - it's preinstalled on NixOS runners
      # - run: cd mobile && nix develop . --command flutter pub get
      - run: cd mobile && nix develop . --command just client-gen
      - run: cd mobile && nix develop . --command flutter build apk --debug

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: mobile/build/app/outputs/flutter-apk/app-debug.apk

      - uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: latest-master
          prerelease: true
          files: mobile/build/app/outputs/flutter-apk/app-debug.apk
          body: "Auto-generated release from master branch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
