name: Release Server Binary

on:
  push:
    # paths: ['flake.nix', 'backend/**', '.github/workflows/release_server.yml', 'web/**']
    # branches: ['master']
    tags:
      - 'v*.*.*'  # Trigger on version tags (e.g., v1.0.0)
  workflow_dispatch:

# Automatically cancels any existing runs in the same group
# Applies to jobs in the same workflow only
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Setup Nix
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      # Build the bundle
      - name: Build bundle
        run: nix bundle .#server

      # Generate changelog
      - name: Generate changelog
        run: |
          nix develop .#release --command git cliff --tag ${{ github.ref_name }} -o CHANGELOG.md

      - uses: actions/upload-artifact@v4
        with:
          name: server-build
          path: yausma-server-arx

      - uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          # files: result/bin/run-server-prod
          files: yausma-server-arx
          body_file: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
