name: Release Please

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ master ]  # Or your release branch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git cliff to work

      # Setup Nix
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Configure Git
        run: |
          git config user.name "CI/CD"
          git config user.email "ci@yausma.org"

      - name: Run release process
        run: nix develop . --command just release

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true  # Push tags as well
          branch: ${{ github.ref_name }}
