name: Release & Deploy Server

on:
  push:
    paths: ['flake.nix', 'backend/**', '.github/workflows/release_server.yml']
    branches: ['master']

# Automatically cancels any existing runs in the same group
# Applies to jobs in the same workflow only
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Nix
      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      # Build the bundle
      - name: Build bundle
        run: nix bundle .#server

      - uses: actions/upload-artifact@v4
        with:
          name: server-build
          path: yausma-server-arx

      - uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: latest-master
          prerelease: true
          # files: result/bin/run-server-prod
          files: yausma-server-arx
          body: "Auto-generated release from master branch [Server]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # # Create release
      # - name: Create Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       result/bin/*
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy-server:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -t 'pkill backend && pkill yausma-server && curl -L https://github.com/YAUSMA-Team/YAUSMA/releases/download/latest-master/yausma-server-arx | sh -s &'
